//tasks
export const FETCH_USER_TASKS = "FETCH_USER_TASKS";
export const GET_CURRENT_TASK = "GET_CURRENT_TASK";
export const ADD_TASK = "ADD_TASK";
export const SET_TASK_ERROR = "SET_TASK_ERROR ";
export const UPDATE_TASK = "UPDATE_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const FILTER_TASKS = "FILTER_TASKS";
export const TASKS_FETCH_FAIL = "TASKS_FETCH_FAIL";
export const CLEAR_FILTER_TASKS = "CLEAR_FILTER_TASKS";
export const SET_CURRENT_TASK = "SET_CURRENT_TASK";
export const CLEAR_CURRENT_TASK = "CLEAR_CURRENT_TASK";

//TaskColumn
export const GET_ALL_TASKCOLUMNS = "GET_ALL_TASKCOLUMNS";
export const ADD_TASKCOLUMN = "ADD_TASKCOLUMN";
export const UPDATE_TASKCOLUMN = "UPDATE_TASKCOLUMN";
export const UPDATE_ALL_TASKCOLUMN = "UPDATE_ALL_TASKCOLUMN";
export const DELETE_TASKCOLUMN = "DELETE_TASKCOLUMN";
export const SET_TASKCOLUMN_ERROR = "SET_TASKCOLUMN_ERROR";

//utilities
export const SET_IS_EDITING = "SET_IS_EDITING";
export const SHOW_MODAL = "SHOW_MODAL";
export const SET_LOADING = "SET_LOADING";

//Todos
export const ADD_TODO = "ADD_TODO";
export const GET_ALL_TASK_CURRENT_TASKCOLUMN =
  "GET_ALL_TASK_CURRENT_TASKCOLUMN";
export const GET_TODO = "GET_TODO";
export const UPDATE_TODO = "UPDATE_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const FILTER_TODO = "ADD_TODO";
export const SET_CURRENT_TODO = "SET_CURRENT_TODO";
export const CLEAR_CURRENT_TODO = "CLEAR_CURRENT_TODO";

//auth
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_ALERT";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_USER_ERROR = "SET_USER_ERROR";
export const SEARCH_USER = "SEARCH_USER";
