//tasks
export const FETCH_USER_TASKS = "FETCH_USER_TASKS";
export const GET_CURRENT_TASK = "GET_CURRENT_TASK";
export const ADD_TASK = "ADD_TASK";
export const SET_TASK_ERROR = "SET_TASK_ERROR ";
export const UPDATE_TASK = "UPDATE_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const FILTER_TASKS = "FILTER_TASKS";
export const TASKS_FETCH_FAIL = "TASKS_FETCH_FAIL";
export const CLEAR_FILTER_TASKS = "CLEAR_FILTER_TASKS";
export const SET_CURRENT_TASK = "SET_CURRENT_TASK";
export const CLEAR_CURRENT_TASK = "CLEAR_CURRENT_TASK";

//TaskColumn
export const GET_ALL_TASKCOLUMNS = "GET_ALL_TASKCOLUMNS";
export const ADD_TASKCOLUMN = "ADD_TASKCOLUMN";
export const UPDATE_TASKCOLUMN = "UPDATE_TASKCOLUMN";
export const UPDATE_ALL_TASKCOLUMN = "UPDATE_ALL_TASKCOLUMN";
export const DELETE_TASKCOLUMN = "DELETE_TASKCOLUMN";
export const CLEAR_TASKCOLUMNS = "CLEAR_TASKCOLUMNS";
export const SET_TASKCOLUMN_ERROR = "SET_TASKCOLUMN_ERROR";

//utilities
export const SET_IS_EDITING = "SET_IS_EDITING";
export const SHOW_MODAL = "SHOW_MODAL";
export const SET_LOADING = "SET_LOADING";

//Todos
export const GET_TODO = "GET_TODO";
export const GET_TODO_CONTENTS = "GET_TODO_CONTENTS";
export const SET_TODO_ERROR = "SET_TODO_ERROR";

//auth
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_ALERT";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_USER_ERROR = "SET_USER_ERROR";
export const SEARCH_USER = "SEARCH_USER";

//Contributors
export const ADD_CONTRIBUTOR = "ADD_CONTRIBUTOR";
export const SEARCH_CONTRIBUTORS = "SEARCH_CONTRIBUTORS";
export const CLEAR_SEARCH_CONTRIBUTORS = "CLEAR_SEARCH_CONTRIBUTORS";
export const SET_CONTRIBUTORS_ERROR = "SET_CONTRIBUTORS_ERROR";
export const GET_CONTRIBUTOR_INVITES = "GET_CONTRIBUTOR_INVITES";
export const GET_CONTRIBUTIONS = "GET_CONTRIBUTIONS";

//notifications
export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";
export const CLICKED_NOTIFICATION = "CLICKED_NOTIFICATION";
export const SET_NOTIFICATION_ERROR = "SET_NOTIFICATION_ERROR";
export const UPDATE_NOTIFICATION_COUNT = "UPDATE_NOTIFICATION_COUNT";
export const UPDATE_NOTIFICATION = "UPDATE_NOTIFICATION";
