//tasks
export const GET_CURRENT_TASK = "GET_CURRENT_TASK";
export const ADD_TASK = "ADD_TASK";
export const UPDATE_TASK = "UPDATE_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const FILTER_TASKS = "FILTER_TASKS";
export const CLEAR_FILTER_TASKS = "CLEAR_FILTER_TASKS";
export const SET_CURRENT_TASK = "SET_CURRENT_TASK";
export const CLEAR_CURRENT_TASK = "CLEAR_CURRENT_TASK";

//TaskColumn
export const GET_ALL_TASKCOLUMNS = "GET_ALL_TASKCOLUMNS";
export const ADD_TASKCOLUMN = "ADD_TASKCOLUMN";
export const UPDATE_TASKCOLUMN = "UPDATE_TASKCOLUMN";
export const UPDATE_ALL_TASKCOLUMN = "UPDATE_ALL_TASKCOLUMN";
export const DELETE_TASKCOLUMN = "DELETE_TASKCOLUMN";
export const IS_LOADING = "IS_LOADING";

//utilities
export const SET_IS_EDITING = "SET_IS_EDITING";
export const SHOW_MODAL = "SHOW_MODAL";

//Todos
export const ADD_TODO = "ADD_TODO";
export const GET_ALL_TASK_CURRENT_TASKCOLUMN =
  "GET_ALL_TASK_CURRENT_TASKCOLUMN";
export const GET_TODO = "GET_TODO";
export const UPDATE_TODO = "UPDATE_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const FILTER_TODO = "ADD_TODO";
export const SET_CURRENT_TODO = "SET_CURRENT_TODO";
export const CLEAR_CURRENT_TODO = "CLEAR_CURRENT_TODO";
